/* Auto-generated by png_to_rgb565.mjs -- do not edit */
#ifndef __EMOJI_DATA_H
#define __EMOJI_DATA_H

#include <stdint.h>

#define EMOJI_COUNT  20
#define EMOJI_WIDTH  64
#define EMOJI_HEIGHT 64

extern const uint8_t * const emoji_table[EMOJI_COUNT];
extern const char * const emoji_names[EMOJI_COUNT];

#endif /* __EMOJI_DATA_H */
