#!/usr/bin/env python3
"""
PNG to RGB565 C array converter for embedded LCD displays.

Converts emoji/icon PNG images into C source files with RGB565 (16-bit color)
pixel data suitable for use with LCD_Show_Image() on STM32 boards.

Usage:
    python png_to_rgb565.py --input <png_dir> --output <output_dir>

Input directory should contain PNG files named with a leading index for ordering,
e.g. 00_smile.png, 01_laugh.png, etc.
"""

import argparse
import os
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Install with: pip install Pillow")
    sys.exit(1)

# Default emoji list (name without extension)
DEFAULT_EMOJIS = [
    "Smile", "Laugh", "Sad", "Angry", "Surprise", "Cool",
    "Heart", "Star", "Thumb", "Clap", "Fire", "Rocket",
]


def image_to_rgb565(img: Image.Image, width: int, height: int) -> bytes:
    """Convert a PIL Image to RGB565 byte array (high byte first)."""
    img = img.resize((width, height), Image.LANCZOS)
    img = img.convert("RGBA")
    background = Image.new("RGBA", (width, height), (0, 0, 0, 255))
    img = Image.alpha_composite(background, img).convert("RGB")

    pixels = list(img.getdata())
    result = bytearray()
    for r, g, b in pixels:
        rgb565 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        result.append((rgb565 >> 8) & 0xFF)
        result.append(rgb565 & 0xFF)
    return bytes(result)


def format_c_array(data: bytes, bytes_per_line: int = 16) -> str:
    """Format bytes as a C array initializer."""
    lines = []
    for i in range(0, len(data), bytes_per_line):
        chunk = data[i:i + bytes_per_line]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk))
    return ",\n".join(lines)


def generate_emoji_data_c(emoji_data: list, width: int, height: int) -> str:
    """Generate emoji_data.c content."""
    lines = []
    lines.append("/* Auto-generated by png_to_rgb565.py -- do not edit */")
    lines.append("#include \"emoji_data.h\"")
    lines.append("")

    array_size = width * height * 2

    for name, data in emoji_data:
        safe_name = name.lower().replace(" ", "_")
        lines.append(f"const uint8_t emoji_{safe_name}[{array_size}] = {{")
        lines.append(format_c_array(data))
        lines.append("};")
        lines.append("")

    # Table of pointers
    lines.append(f"const uint8_t * const emoji_table[EMOJI_COUNT] = {{")
    names = [name.lower().replace(" ", "_") for name, _ in emoji_data]
    lines.append("    " + ",\n    ".join(f"emoji_{n}" for n in names))
    lines.append("};")
    lines.append("")

    # Name strings
    lines.append("const char * const emoji_names[EMOJI_COUNT] = {")
    lines.append("    " + ",\n    ".join(f'"{name}"' for name, _ in emoji_data))
    lines.append("};")
    lines.append("")

    return "\n".join(lines)


def generate_emoji_data_h(count: int, width: int, height: int) -> str:
    """Generate emoji_data.h content."""
    lines = []
    lines.append("/* Auto-generated by png_to_rgb565.py -- do not edit */")
    lines.append("#ifndef __EMOJI_DATA_H")
    lines.append("#define __EMOJI_DATA_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define EMOJI_COUNT  {count}")
    lines.append(f"#define EMOJI_WIDTH  {width}")
    lines.append(f"#define EMOJI_HEIGHT {height}")
    lines.append("")
    lines.append("extern const uint8_t * const emoji_table[EMOJI_COUNT];")
    lines.append("extern const char * const emoji_names[EMOJI_COUNT];")
    lines.append("")
    lines.append("#endif /* __EMOJI_DATA_H */")
    lines.append("")
    return "\n".join(lines)


def find_png_files(input_dir: str) -> list:
    """Find and sort PNG files in the input directory."""
    png_files = []
    for f in sorted(os.listdir(input_dir)):
        if f.lower().endswith(".png"):
            png_files.append(os.path.join(input_dir, f))
    return png_files


def main():
    parser = argparse.ArgumentParser(description="Convert PNG emoji images to RGB565 C arrays")
    parser.add_argument("--input", required=True, help="Directory containing PNG files")
    parser.add_argument("--output", required=True, help="Output directory for .c and .h files")
    parser.add_argument("--width", type=int, default=64, help="Output image width (default: 64)")
    parser.add_argument("--height", type=int, default=64, help="Output image height (default: 64)")
    args = parser.parse_args()

    png_files = find_png_files(args.input)
    if not png_files:
        print(f"Error: No PNG files found in {args.input}")
        sys.exit(1)

    print(f"Found {len(png_files)} PNG files")

    emoji_data = []
    for png_path in png_files:
        name = Path(png_path).stem
        # Strip leading numbers and separators (e.g. "00_smile" -> "Smile")
        parts = name.split("_", 1)
        if len(parts) > 1 and parts[0].isdigit():
            clean_name = parts[1].capitalize()
        else:
            clean_name = name.capitalize()

        print(f"  Converting: {png_path} -> {clean_name}")
        img = Image.open(png_path)
        data = image_to_rgb565(img, args.width, args.height)
        emoji_data.append((clean_name, data))

    os.makedirs(args.output, exist_ok=True)

    c_content = generate_emoji_data_c(emoji_data, args.width, args.height)
    h_content = generate_emoji_data_h(len(emoji_data), args.width, args.height)

    c_path = os.path.join(args.output, "emoji_data.c")
    h_path = os.path.join(args.output, "emoji_data.h")

    with open(c_path, "w", encoding="utf-8") as f:
        f.write(c_content)
    print(f"Written: {c_path} ({os.path.getsize(c_path)} bytes)")

    with open(h_path, "w", encoding="utf-8") as f:
        f.write(h_content)
    print(f"Written: {h_path} ({os.path.getsize(h_path)} bytes)")

    total_pixel_bytes = sum(len(d) for _, d in emoji_data)
    print(f"\nSummary: {len(emoji_data)} emojis, {total_pixel_bytes} bytes total pixel data")


if __name__ == "__main__":
    main()
