/**
 * PNG to RGB565 converter for embedded LCD displays.
 * Uses pngjs (pure JS, no native dependencies).
 *
 * Usage: node tools/png_to_rgb565.mjs
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "fs";
import { join, basename, sep } from "path";
import { PNG } from "pngjs";

const INPUT_DIR = "tools/emoji_png";
const OUTPUT_DIR = "applications/A13_basic_emoji_lcd";
const IMG_W = 64;
const IMG_H = 64;

const EMOJI_NAMES = [
  "Smile", "Laugh", "Sad", "Angry", "Surprise", "Cool",
  "Heart", "Star", "Thumb", "Clap", "Fire", "Rocket",
];

// Read and sort PNG files
const files = readdirSync(INPUT_DIR)
  .filter(f => f.toLowerCase().endsWith(".png"))
  .sort();

if (files.length === 0) {
  console.error("No PNG files found in", INPUT_DIR);
  process.exit(1);
}
console.log(`Found ${files.length} PNG files`);

/**
 * Convert PNG buffer to RGB565 byte array (high byte first).
 * Resize to IMG_W x IMG_H, composite onto black background.
 */
function pngToRGB565(buf) {
  const png = PNG.sync.read(buf);
  const srcW = png.width;
  const srcH = png.height;
  const out = Buffer.alloc(IMG_W * IMG_H * 2);

  for (let y = 0; y < IMG_H; y++) {
    for (let x = 0; x < IMG_W; x++) {
      // Nearest-neighbor resize
      const sx = Math.floor(x * srcW / IMG_W);
      const sy = Math.floor(y * srcH / IMG_H);
      const si = (sy * srcW + sx) * 4;

      let r = png.data[si];
      let g = png.data[si + 1];
      let b = png.data[si + 2];
      const a = png.data[si + 3] / 255;

      // Composite onto black background
      r = Math.round(r * a);
      g = Math.round(g * a);
      b = Math.round(b * a);

      const rgb565 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
      const oi = (y * IMG_W + x) * 2;
      out[oi] = (rgb565 >> 8) & 0xFF;
      out[oi + 1] = rgb565 & 0xFF;
    }
  }
  return out;
}

/**
 * Format buffer as C hex array initializer.
 */
function formatCArray(buf, bytesPerLine = 16) {
  const lines = [];
  for (let i = 0; i < buf.length; i += bytesPerLine) {
    const chunk = buf.slice(i, Math.min(i + bytesPerLine, buf.length));
    lines.push("    " + Array.from(chunk).map(b => `0x${b.toString(16).padStart(2, "0").toUpperCase()}`).join(", "));
  }
  return lines.join(",\n");
}

// Process all PNGs
const emojis = [];
for (let i = 0; i < files.length; i++) {
  const filePath = join(INPUT_DIR, files[i]);
  const name = EMOJI_NAMES[i] || basename(files[i], ".png");
  console.log(`  Converting: ${files[i]} -> ${name}`);
  const buf = readFileSync(filePath);
  const rgb565 = pngToRGB565(buf);
  emojis.push({ name, data: rgb565 });
}

mkdirSync(OUTPUT_DIR, { recursive: true });

// Generate emoji_data.h
const headerContent = `/* Auto-generated by png_to_rgb565.mjs -- do not edit */
#ifndef __EMOJI_DATA_H
#define __EMOJI_DATA_H

#include <stdint.h>

#define EMOJI_COUNT  ${emojis.length}
#define EMOJI_WIDTH  ${IMG_W}
#define EMOJI_HEIGHT ${IMG_H}

extern const uint8_t * const emoji_table[EMOJI_COUNT];
extern const char * const emoji_names[EMOJI_COUNT];

#endif /* __EMOJI_DATA_H */
`;

// Generate emoji_data.c
const arraySize = IMG_W * IMG_H * 2;
let sourceContent = `/* Auto-generated by png_to_rgb565.mjs -- do not edit */\n`;
sourceContent += `#include "emoji_data.h"\n\n`;

for (const { name, data } of emojis) {
  const safeName = name.toLowerCase();
  sourceContent += `const uint8_t emoji_${safeName}[${arraySize}] = {\n`;
  sourceContent += formatCArray(data) + "\n";
  sourceContent += `};\n\n`;
}

sourceContent += `const uint8_t * const emoji_table[EMOJI_COUNT] = {\n`;
sourceContent += emojis.map(e => `    emoji_${e.name.toLowerCase()}`).join(",\n");
sourceContent += `\n};\n\n`;

sourceContent += `const char * const emoji_names[EMOJI_COUNT] = {\n`;
sourceContent += emojis.map(e => `    "${e.name}"`).join(",\n");
sourceContent += `\n};\n`;

// Write files
const hPath = join(OUTPUT_DIR, "emoji_data.h");
const cPath = join(OUTPUT_DIR, "emoji_data.c");
writeFileSync(hPath, headerContent);
writeFileSync(cPath, sourceContent);

console.log(`\nWritten: ${hPath} (${headerContent.length} bytes)`);
console.log(`Written: ${cPath} (${sourceContent.length} bytes)`);
console.log(`Summary: ${emojis.length} emojis, ${arraySize * emojis.length} bytes total pixel data`);
