/**
 * PNG to RGB565 converter for embedded LCD displays.
 * Processes 20 face emoji PNGs for A13 example.
 *
 * Usage: node tools/png_to_rgb565_v2.mjs
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "fs";
import { join, basename } from "path";
import { PNG } from "pngjs";

const INPUT_DIR = "tools/emoji_png";
const OUTPUT_DIR = "applications/A13_basic_emoji_lcd";
const IMG_W = 64;
const IMG_H = 64;

const EMOJI_NAMES = [
  "Grinning", "Tears_of_Joy", "Winking", "Heart_Eyes", "Cool",
  "Neutral", "Unamused", "Disappointed", "Angry", "Crying",
  "Surprised", "Screaming", "Flushed", "Sleeping", "Dizzy",
  "Money_Mouth", "Nerd", "Thinking", "Hugging", "Exploding_Head",
];

function pngToRGB565(buf) {
  const png = PNG.sync.read(buf);
  const srcW = png.width;
  const srcH = png.height;
  const out = Buffer.alloc(IMG_W * IMG_H * 2);

  for (let y = 0; y < IMG_H; y++) {
    for (let x = 0; x < IMG_W; x++) {
      const sx = Math.floor(x * srcW / IMG_W);
      const sy = Math.floor(y * srcH / IMG_H);
      const si = (sy * srcW + sx) * 4;

      let r = png.data[si];
      let g = png.data[si + 1];
      let b = png.data[si + 2];
      const a = png.data[si + 3] / 255;

      r = Math.round(r * a);
      g = Math.round(g * a);
      b = Math.round(b * a);

      const rgb565 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
      const oi = (y * IMG_W + x) * 2;
      out[oi] = (rgb565 >> 8) & 0xFF;
      out[oi + 1] = rgb565 & 0xFF;
    }
  }
  return out;
}

function formatCArray(buf) {
  const lines = [];
  const bpl = 16;
  for (let i = 0; i < buf.length; i += bpl) {
    const chunk = buf.slice(i, Math.min(i + bpl, buf.length));
    lines.push("    " + Array.from(chunk).map(b => `0x${b.toString(16).padStart(2, "0").toUpperCase()}`).join(", "));
  }
  return lines.join(",\n");
}

const files = readdirSync(INPUT_DIR).filter(f => f.endsWith(".png")).sort();
console.log(`Found ${files.length} PNG files`);

const emojis = [];
for (let i = 0; i < files.length; i++) {
  const name = EMOJI_NAMES[i] || basename(files[i], ".png");
  console.log(`  ${files[i]} -> ${name}`);
  const buf = readFileSync(join(INPUT_DIR, files[i]));
  const rgb565 = pngToRGB565(buf);
  emojis.push({ name, data: rgb565 });
}

mkdirSync(OUTPUT_DIR, { recursive: true });

// emoji_data.h
const header = `/* Auto-generated by png_to_rgb565.mjs -- do not edit */
#ifndef __EMOJI_DATA_H
#define __EMOJI_DATA_H

#include <stdint.h>

#define EMOJI_COUNT  ${emojis.length}
#define EMOJI_WIDTH  ${IMG_W}
#define EMOJI_HEIGHT ${IMG_H}

extern const uint8_t * const emoji_table[EMOJI_COUNT];
extern const char * const emoji_names[EMOJI_COUNT];

#endif /* __EMOJI_DATA_H */
`;

// emoji_data.c
const arraySize = IMG_W * IMG_H * 2;
let source = `/* Auto-generated by png_to_rgb565.mjs -- do not edit */\n`;
source += `#include "emoji_data.h"\n\n`;

for (const { name, data } of emojis) {
  source += `const uint8_t emoji_${name.toLowerCase()}[${arraySize}] = {\n`;
  source += formatCArray(data) + "\n};\n\n";
}

source += `const uint8_t * const emoji_table[EMOJI_COUNT] = {\n`;
source += emojis.map(e => `    emoji_${e.name.toLowerCase()}`).join(",\n");
source += `\n};\n\n`;

source += `const char * const emoji_names[EMOJI_COUNT] = {\n`;
source += emojis.map(e => `    "${e.name.replace(/_/g, " ")}"`).join(",\n");
source += `\n};\n`;

writeFileSync(join(OUTPUT_DIR, "emoji_data.h"), header);
writeFileSync(join(OUTPUT_DIR, "emoji_data.c"), source);

console.log(`\nDone: ${emojis.length} emojis, ${arraySize * emojis.length} bytes total`);
console.log(`  -> ${join(OUTPUT_DIR, "emoji_data.h")}`);
console.log(`  -> ${join(OUTPUT_DIR, "emoji_data.c")}`);
